openapi: 3.0.0
info:
  title: Emergency Alert API
  description: Sends and manages real-time emergency alerts and notifications.
  version: 1.0.0
paths:
  /alerts/{alert_id}:
    get:
      summary: Retrieve a specific emergency alert by its ID
      parameters:
        - name: alert_id
          in: path
          required: true
          description: The unique ID of the alert
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved the alert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alert'
        "404":
          description: Alert not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "400":
          description: Alert ID is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /alerts:
    post:
      summary: Send a new emergency alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlertInput'
      responses:
        "201":
          description: Emergency alert created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertResponse'
        "400":
          description: Missing title or message in the request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Alert:
      type: object
      properties:
        title:
          type: string
          example: "Campus Evacuation"
        message:
          type: string
          example: "All students must evacuate the campus immediately."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"
    AlertInput:
      type: object
      required:
        - title
        - message
      properties:
        title:
          type: string
          example: "Campus Evacuation"
        message:
          type: string
          example: "All students must evacuate the campus immediately."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"
    AlertResponse:
      type: object
      properties:
        id:
          type: string
          example: "alert_12345"
        title:
          type: string
          example: "Campus Evacuation"
        message:
          type: string
          example: "All students must evacuate the campus immediately."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "An error occurred."
