openapi: 3.0.0
info:
  title: Incident Reporting API
  description: Provides endpoints to report and manage incidents.
  version: 1.0.0
paths:
  /incidents:
    get:
      summary: Retrieve all incident alerts
      description: Retrieve all incident alerts stored in the Firebase database.
      responses:
        "200":
          description: List of all incident alerts
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/IncidentAlert'
        "500":
          description: Internal server error
    post:
      summary: Submit a new incident alert
      description: Create a new incident alert.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncidentAlertInput'
      responses:
        "201":
          description: Incident created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "incident_12345"
                  alert:
                    $ref: '#/components/schemas/IncidentAlert'
        "500":
          description: Internal server error

  /incidents/{incident_id}:
    get:
      summary: Retrieve a specific incident alert by ID
      description: Get the details of a specific incident alert using its ID.
      parameters:
        - name: incident_id
          in: path
          required: true
          description: The ID of the incident to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Incident retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentAlert'
        "404":
          description: Incident not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

    put:
      summary: Update an existing incident alert
      description: Update the details of an incident alert using its ID.
      parameters:
        - name: incident_id
          in: path
          required: true
          description: The ID of the incident to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IncidentAlertInput'
      responses:
        "200":
          description: Incident updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "incident_12345"
                  alert:
                    $ref: '#/components/schemas/IncidentAlert'
        "400":
          description: Incident ID is required for update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

    delete:
      summary: Delete an incident alert
      description: Delete an incident alert by its ID.
      parameters:
        - name: incident_id
          in: path
          required: true
          description: The ID of the incident to delete
          schema:
            type: string
      responses:
        "204":
          description: Incident deleted successfully
        "400":
          description: Incident ID is required for deletion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

components:
  schemas:
    IncidentAlert:
      type: object
      properties:
        id:
          type: string
          example: incident_12345
        title:
          type: string
          example: "Fire in the building"
        message:
          type: string
          example: "There is a fire on the 2nd floor. Evacuate immediately."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"

    IncidentAlertInput:
      type: object
      required:
        - title
        - message
      properties:
        title:
          type: string
          example: "Fire in the building"
        message:
          type: string
          example: "There is a fire on the 2nd floor. Evacuate immediately."

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Incident with ID incident_12345 not found"

