openapi: 3.0.0
info:
  title: Notification Services API
  description: Manages real-time notifications for emergency alerts and announcements.
  version: 1.0.0
paths:
  /notifications:
    get:
      summary: Retrieve all notifications
      description: Fetch all notifications from the Firebase database.
      responses:
        "200":
          description: List of all notifications
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/NotificationData'
        "500":
          description: Internal server error

    post:
      summary: Create a new notification
      description: Add a new notification to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationDataInput'
      responses:
        "201":
          description: Notification created successfully
          content:
            application/json:
              schema:
                type: string
                example: "New notification added with ID: notification_123"
        "400":
          description: Invalid notification data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

  /notifications/{notification_id}:
    get:
      summary: Retrieve a specific notification
      description: Fetch a notification by its ID.
      parameters:
        - name: notification_id
          in: path
          required: true
          description: The ID of the notification to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Notification retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationData'
        "404":
          description: Notification not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

    delete:
      summary: Delete a specific notification
      description: Remove a notification by its ID.
      parameters:
        - name: notification_id
          in: path
          required: true
          description: The ID of the notification to delete
          schema:
            type: string
      responses:
        "200":
          description: Notification deleted successfully
          content:
            application/json:
              schema:
                type: string
                example: "Notification with ID notification_123 deleted"
        "400":
          description: Notification ID is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Notification not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

components:
  schemas:
    NotificationData:
      type: object
      properties:
        notification_id:
          type: string
          example: "notification_123"
        message:
          type: string
          example: "This is a test notification."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"
        type:
          type: string
          example: "info"
        user_id:
          type: string
          example: "user_456"

    NotificationDataInput:
      type: object
      required:
        - notification_id
        - message
        - timestamp
        - type
        - user_id
      properties:
        notification_id:
          type: string
          example: "notification_123"
        message:
          type: string
          example: "This is a test notification."
        timestamp:
          type: string
          format: date-time
          example: "2024-08-25T14:15:00Z"
        type:
          type: string
          example: "info"
        user_id:
          type: string
          example: "user_456"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Notification ID is required"
