openapi: 3.0.0
info:
  title: Safety Resource API
  description: Provides access to safety resources and emergency contact information.
  version: 1.0.0
paths:
  /resources:
    get:
      summary: Retrieve all safety resources
      description: Fetch all safety resources from the Firebase database.
      responses:
        "200":
          description: List of all safety resources
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/SafetyResourceData'
        "500":
          description: Internal server error

    post:
      summary: Create a new safety resource
      description: Add a new safety resource to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SafetyResourceDataInput'
      responses:
        "201":
          description: Safety resource created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "resource_123"
                  name:
                    type: string
                    example: "Fire Extinguisher"
                  description:
                    type: string
                    example: "A portable device for extinguishing small fires."
        "400":
          description: Invalid resource data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

  /resources/{id}:
    get:
      summary: Retrieve a specific safety resource
      description: Fetch a safety resource by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the resource to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Safety resource retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SafetyResourceData'
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

    put:
      summary: Update a specific safety resource
      description: Modify an existing safety resource by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the resource to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SafetyResourceDataInput'
      responses:
        "200":
          description: Safety resource updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "resource_123"
                  name:
                    type: string
                    example: "Fire Extinguisher"
                  description:
                    type: string
                    example: "Updated description of the fire extinguisher."
        "400":
          description: Invalid resource data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

    delete:
      summary: Delete a specific safety resource
      description: Remove a safety resource by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the resource to delete
          schema:
            type: string
      responses:
        "204":
          description: Resource deleted successfully
        "400":
          description: Resource ID is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal server error

components:
  schemas:
    SafetyResourceData:
      type: object
      properties:
        id:
          type: string
          example: "resource_123"
        name:
          type: string
          example: "Fire Extinguisher"
        description:
          type: string
          example: "A portable device for extinguishing small fires."

    SafetyResourceDataInput:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: "Fire Extinguisher"
        description:
          type: string
          example: "A portable device for extinguishing small fires."

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Resource not found"
